/*Copyright 2020 Alex Bieliakov*/

#ifndef EXAMPLE_DOWNLOAD_GTEST_GMOCK_INCLUDE_I_BIG_FORMULA_HPP_
#define EXAMPLE_DOWNLOAD_GTEST_GMOCK_INCLUDE_I_BIG_FORMULA_HPP_

class IBigFormula {
public:
  virtual int BigCount(int value) = 0;
};

#endif // EXAMPLE_DOWNLOAD_GTEST_GMOCK_INCLUDE_I_BIG_FORMULA_HPP_
